### ISSUE TITLE
Compatibility with BRAT

### ISSUE THREAD

**Issue by abdcef** [nicucalcea/obsidian-tasks-todo-txt#1]
Thanks for developing this plugin. I was wondering if you could make it compatible with BRAT to make it easier to install and update. Do you have two-way sync feature on your roadmap? It will be great to have that enabled.

**Comment by nicucalcea** [comment]
BRAT compatibility sounds good, I'll look into it when I have a minute.

Two-way sync would be great, but I don't know how I'd implement that. Since it's all plaintext. I can't add any hidden metadata to the tasks in `todo.txt` that would help me link them back to their counterparts in Obsidian.

**Comment by abdcef** [comment]
Thank you!
Let me play around with it and see if I get any ideas :)

**Comment by TfTHacker** [comment]
Hi there. I am the dev behind BRAT 🤓.

I was looking at your release, and I see you have not tagged it with a release number. For a release to be picked up by Obsidian (or BRAT) for that matter, it needs to have a tag added to the release. The tag has to match the version number in your manifest.json.

My guess is Obsidian would not download this either once you have it in the community list.

**Comment by nicucalcea** [comment]
I have tagged it with the release number. I don't use BRAT, so feel free to reopen the issue if it doesn't work.

**Comment by TfTHacker** [comment]
Great. But it doesn't matter if you use BRAT. Obsidian will not download releases if not tagged with the version number defined in manifest.json. Since BRAT is a testing tool to find problems, it turns out you do use BRAT 🙃.

I wish you success with your plugin.

**Comment by nicucalcea** [comment]
Thanks for the information! I wrote this plugin for my personal use and I don't think it's a particularly elegant solution, so I don't really want it to be picked up by Obsidian. But I'm happy to do any minor tweaks if it helps others.

**Comment by TfTHacker** [comment]
To bad, its an appealing concept. Though... not having to deal with the support calls is an advantage :-)
