### ISSUE TITLE
date syntax

### ISSUE THREAD

**Issue by abdcef** [nicucalcea/obsidian-tasks-todo-txt#3]
I noticed that the date syntax is not changed. Obsidian dates are [[YYYY-MM-DD]] and todotxt format is YYYY-MM-DD

**Comment by nicucalcea** [comment]
Can you give me an example? The only place I use dates in my notes is due dates for my tasks, and they're in this format: https://obsidian-tasks-group.github.io/obsidian-tasks/getting-started/dates/#-due

**Comment by abdcef** [comment]
I understand now. In my case, the date syntax was using the block references for the daily note. I can fix that at my end. Thanks
